apiVersion: v1
kind: ConfigMap
metadata:
  name: urbaninvest-config
  namespace: urbaninvest
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "urbaninvest"
  DB_USER: "urbaninvest"
  DB_PASSWORD: "urbaninvest123"
  APP_ENV: "production"
