apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urbaninvest-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: urbaninvest.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: urbaninvest-service
            port:
              number: 80
